/**
 * JBoss, Home of Professional Open Source.
 * Copyright 2012, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 * 
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 * 
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 * 
 */
package org.jboss.jca.adapters.sap.spi.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.jboss.jca.adapters.sap.spi.util.SpiAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SpiItemProviderAdapterFactory extends SpiAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SpiItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.jboss.jca.adapters.sap.spi.ConnectionRequestInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConnectionRequestInfoItemProvider connectionRequestInfoItemProvider;

	/**
	 * This creates an adapter for a {@link org.jboss.jca.adapters.sap.spi.ConnectionRequestInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConnectionRequestInfoAdapter() {
		if (connectionRequestInfoItemProvider == null) {
			connectionRequestInfoItemProvider = new ConnectionRequestInfoItemProvider(this);
		}

		return connectionRequestInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.jboss.jca.adapters.sap.spi.DefaultConnectionManager} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefaultConnectionManagerItemProvider defaultConnectionManagerItemProvider;

	/**
	 * This creates an adapter for a {@link org.jboss.jca.adapters.sap.spi.DefaultConnectionManager}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefaultConnectionManagerAdapter() {
		if (defaultConnectionManagerItemProvider == null) {
			defaultConnectionManagerItemProvider = new DefaultConnectionManagerItemProvider(this);
		}

		return defaultConnectionManagerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.jboss.jca.adapters.sap.spi.LocalTransaction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocalTransactionItemProvider localTransactionItemProvider;

	/**
	 * This creates an adapter for a {@link org.jboss.jca.adapters.sap.spi.LocalTransaction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocalTransactionAdapter() {
		if (localTransactionItemProvider == null) {
			localTransactionItemProvider = new LocalTransactionItemProvider(this);
		}

		return localTransactionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.jboss.jca.adapters.sap.spi.ManagedConnectionFactory} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ManagedConnectionFactoryItemProvider managedConnectionFactoryItemProvider;

	/**
	 * This creates an adapter for a {@link org.jboss.jca.adapters.sap.spi.ManagedConnectionFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createManagedConnectionFactoryAdapter() {
		if (managedConnectionFactoryItemProvider == null) {
			managedConnectionFactoryItemProvider = new ManagedConnectionFactoryItemProvider(this);
		}

		return managedConnectionFactoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.jboss.jca.adapters.sap.spi.ManagedConnection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ManagedConnectionItemProvider managedConnectionItemProvider;

	/**
	 * This creates an adapter for a {@link org.jboss.jca.adapters.sap.spi.ManagedConnection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createManagedConnectionAdapter() {
		if (managedConnectionItemProvider == null) {
			managedConnectionItemProvider = new ManagedConnectionItemProvider(this);
		}

		return managedConnectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.jboss.jca.adapters.sap.spi.ManagedConnectionMetaData} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ManagedConnectionMetaDataItemProvider managedConnectionMetaDataItemProvider;

	/**
	 * This creates an adapter for a {@link org.jboss.jca.adapters.sap.spi.ManagedConnectionMetaData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createManagedConnectionMetaDataAdapter() {
		if (managedConnectionMetaDataItemProvider == null) {
			managedConnectionMetaDataItemProvider = new ManagedConnectionMetaDataItemProvider(this);
		}

		return managedConnectionMetaDataItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.jboss.jca.adapters.sap.spi.NonManagedEnvironmentAdmin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NonManagedEnvironmentAdminItemProvider nonManagedEnvironmentAdminItemProvider;

	/**
	 * This creates an adapter for a {@link org.jboss.jca.adapters.sap.spi.NonManagedEnvironmentAdmin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNonManagedEnvironmentAdminAdapter() {
		if (nonManagedEnvironmentAdminItemProvider == null) {
			nonManagedEnvironmentAdminItemProvider = new NonManagedEnvironmentAdminItemProvider(this);
		}

		return nonManagedEnvironmentAdminItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.jboss.jca.adapters.sap.spi.ResourceAdapter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResourceAdapterItemProvider resourceAdapterItemProvider;

	/**
	 * This creates an adapter for a {@link org.jboss.jca.adapters.sap.spi.ResourceAdapter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResourceAdapterAdapter() {
		if (resourceAdapterItemProvider == null) {
			resourceAdapterItemProvider = new ResourceAdapterItemProvider(this);
		}

		return resourceAdapterItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (connectionRequestInfoItemProvider != null) connectionRequestInfoItemProvider.dispose();
		if (defaultConnectionManagerItemProvider != null) defaultConnectionManagerItemProvider.dispose();
		if (localTransactionItemProvider != null) localTransactionItemProvider.dispose();
		if (managedConnectionFactoryItemProvider != null) managedConnectionFactoryItemProvider.dispose();
		if (managedConnectionItemProvider != null) managedConnectionItemProvider.dispose();
		if (managedConnectionMetaDataItemProvider != null) managedConnectionMetaDataItemProvider.dispose();
		if (nonManagedEnvironmentAdminItemProvider != null) nonManagedEnvironmentAdminItemProvider.dispose();
		if (resourceAdapterItemProvider != null) resourceAdapterItemProvider.dispose();
	}

}
